#Server
server:
  port: 8085

#App authentication configurations
security:
  auth:
    google:
      client:
        clientId: abcdddlcr9.apps.googleusercontent.com
    processingUrl: "/login/google"
    token:
      validity: 21600



#Datasource
spring:
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/googleAuth?currentSchema=googlelogin&useTimezone=true&serverTimezone=UTC
    username: googleUser
    password: googleUser
    driverClassName: org.postgresql.Driver
  jpa:
    show-sql: false
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
    database-platform: org.hibernate.dialect.PostgreSQL94Dialect
